### ISSUE TITLE
Support heroku dynamic port - feature request

### ISSUE THREAD

**Issue by ccyang314** [Liby99/keeling-js#4]
Currently, when pushing app to heroku, it will fail to start. Heroku internal port number cannot be read by keeling's config.json. 

Heroku side error message:
`2017-05-07T22:53:44.641798+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

This way should works: 
`app.set('port', process.env.PORT || 3000);`

**Comment by Liby99** [comment]
Fixed~!
So now if you are using $PORT then the port specified in config.json will not be taken into account.

**Comment by Liby99** [comment]
So now if one is using $PORT then the port in config.json will not be taken into account.
